server:
  port: 8100
  servlet:
    context-path: /matricula
spring:
  application:
    name: matricula-service
  config:
    import:
      - optional:configserver:http://localhost:8765/config-server
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
