server:
  port: 8765
spring:
  application:
    name: api-gateway
#  cloud: ## desabilitado pois a configuração de rota será feita em ApiGatewayConfig.
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
