server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cnbs-service
          uri: lb://cnbs-service
          predicates:
            - Path=/cnbs/**
        - id: matricula-service
          uri: lb://matricula-service
          predicates:
            - Path=/matricula/**
        - id: financeiro-service
          uri: lb://financeiro-service
          predicates:
            - Path=/financeiro/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
