services:
  cnbs-serpro-client:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: cnbs-service
    ports:
      - "8081:8080"
    environment:
      - OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx512m -Xms128m -XX:MaxMetaspaceSize=128m
