server:
  port: 8888 # porta padrão para o config server
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marksduarte/config-server
          default-label: main
          timeout: 4
          search-paths:
            - 'cnbs-service*'
